const EVENTS = {
  MONITOR_START: 'MONITOR_START',
  MONITOR_COINS_LOADED: 'MONITOR_COINS_LOADED',
  MONITOR_INIT_COINS: 'MONITOR_INIT_COINS',
  MONITOR_CYCLE: 'MONITOR_CYCLE',
  MONITOR_CHECK_COIN: 'MONITOR_CHECK_COIN',
  MONITOR_MAKE_ORDER: 'MONITOR_MAKE_ORDER',
  MONITOR_ORDER_DONE: 'MONITOR_ORDER_DONE',
  MONITOR_PRICE_CHANGE: 'MONITOR_PRICE_CHANGE',
};

export default EVENTS;
